export default {
  login: "romarinmarin",
  id: 17761936,
  node_id: "MDQ6VXNlcjE3NzYxOTM2",
  avatar_url: "https://avatars.githubusercontent.com/u/17761936?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/romarinmarin",
  html_url: "https://github.com/romarinmarin",
  followers_url: "https://api.github.com/users/romarinmarin/followers",
  following_url:
    "https://api.github.com/users/romarinmarin/following{/other_user}",
  gists_url: "https://api.github.com/users/romarinmarin/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/romarinmarin/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/romarinmarin/subscriptions",
  organizations_url: "https://api.github.com/users/romarinmarin/orgs",
  repos_url: "https://api.github.com/users/romarinmarin/repos",
  events_url: "https://api.github.com/users/romarinmarin/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/romarinmarin/received_events",
  type: "User",
  site_admin: false,
  name: "Romaric Anquetil",
  company: null,
  blog: "http://romaricanquetil.com",
  location: "Rennes",
  email: null,
  hireable: null,
  bio: "Développeur Front end / AngularJS",
  twitter_username: null,
  public_repos: 29,
  public_gists: 0,
  followers: 2,
  following: 0,
  created_at: "2016-03-10T10:18:02Z",
  updated_at: "2021-04-01T09:02:50Z",
};
